[package]
name = "tracing_sim"
version = "0.1.0"
authors = ["Anirudh Sivaraman <sk.anirudh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.6.5"
queues = "1.0.2"
rand="0.3.0"

[lib]
name = "sample_plugin"
path = "src/sample_plugin.rs"
crate-type = ["dylib"]
