[package]
name = "tracing_sim"
version = "0.1.0"
authors = ["Anirudh Sivaraman <sk.anirudh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.1"
libloading = "0.6.5"
queues = "1.0.2"
uuid = { version = "0.8", features = ["serde", "v4"] }

[[bin]]
name = "petgraph_sample"
path = "src/petgraph_sample.rs"

[lib]
name = "plugin_sample"
path = "src/plugin_sample.rs"
crate-type = ["dylib"]
